package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

Recommendation: create a `rpcs.go` file in the same directory as this file and
implement your APIs there.

----------------------------------------------------------------- */

import (
	"backend/pkg/gen"
	"context"
	"fmt"
	"net"

	"buf.build/go/protovalidate"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"google.golang.org/protobuf/proto"

	"google.golang.org/grpc/reflection"

	codefly "github.com/codefly-dev/sdk-go"
	"google.golang.org/grpc"
)

var validator protovalidate.Validator

func init() {
	v, err := protovalidate.New()
	if err != nil {
		panic(fmt.Errorf("failed to create validator: %w", err))
	}
	validator = v
}

func Validate(req proto.Message) error {
	err := validator.Validate(req)
	if err != nil {
		return status.Error(codes.InvalidArgument, err.Error())
	}
	return nil
}

type Configuration struct {
	EndpointGrpcPort uint16
	EndpointHttpPort *uint16
}

// UserServer handles UserService RPCs.
type UserServer struct {
	gen.UnsafeUserServiceServer
}

// OrgServer handles OrganizationService RPCs.
type OrgServer struct {
	gen.UnsafeOrganizationServiceServer
}

// TeamServer handles TeamService RPCs.
type TeamServer struct {
	gen.UnsafeTeamServiceServer
}

// PermServer handles PermissionService RPCs.
type PermServer struct {
	gen.UnsafePermissionServiceServer
}

// IdentServer handles IdentityService RPCs.
type IdentServer struct {
	gen.UnsafeIdentityServiceServer
}

// APIKeyServer handles APIKeyService RPCs.
type APIKeyServer struct {
	gen.UnsafeAPIKeyServiceServer
}

// AuthServer handles AuthService RPCs.
type AuthServer struct {
	gen.UnsafeAuthServiceServer
}

// AuditServer handles AuditService RPCs.
type AuditServer struct {
	gen.UnsafeAuditServiceServer
}

// InvitationServer handles InvitationService RPCs.
type InvitationServer struct {
	gen.UnsafeInvitationServiceServer
}

// AdminServer handles AdminService RPCs.
type AdminServer struct {
	gen.UnsafeAdminServiceServer
}

// GrpcServer wraps all service servers and manages the gRPC lifecycle.
type GrpcServer struct {
	User   *UserServer
	Org    *OrgServer
	Team   *TeamServer
	Perm   *PermServer
	Ident  *IdentServer
	APIKey *APIKeyServer
	Auth   *AuthServer
	Audit      *AuditServer
	Invitation *InvitationServer
	Admin      *AdminServer

	configuration *Configuration
	gRPC          *grpc.Server
	validator     protovalidate.Validator
}

func (s *UserServer) Version(ctx context.Context, req *gen.VersionRequest) (*gen.VersionResponse, error) {
	if err := Validate(req); err != nil {
		return nil, err
	}
	return &gen.VersionResponse{
		Version: codefly.ServiceVersion(),
	}, nil
}

func NewGrpServer(c *Configuration) (*GrpcServer, error) {
	grpcServer := grpc.NewServer()
	v, err := protovalidate.New()
	if err != nil {
		return nil, fmt.Errorf("failed to create validator: %w", err)
	}

	s := &GrpcServer{
		User:          &UserServer{},
		Org:           &OrgServer{},
		Team:          &TeamServer{},
		Perm:          &PermServer{},
		Ident:         &IdentServer{},
		APIKey:        &APIKeyServer{},
		Auth:          &AuthServer{},
		Audit:         &AuditServer{},
		Invitation:    &InvitationServer{},
		Admin:         &AdminServer{},
		configuration: c,
		gRPC:          grpcServer,
		validator:     v,
	}

	gen.RegisterUserServiceServer(grpcServer, s.User)
	gen.RegisterOrganizationServiceServer(grpcServer, s.Org)
	gen.RegisterTeamServiceServer(grpcServer, s.Team)
	gen.RegisterPermissionServiceServer(grpcServer, s.Perm)
	gen.RegisterIdentityServiceServer(grpcServer, s.Ident)
	gen.RegisterAPIKeyServiceServer(grpcServer, s.APIKey)
	gen.RegisterAuthServiceServer(grpcServer, s.Auth)
	gen.RegisterAuditServiceServer(grpcServer, s.Audit)
	gen.RegisterInvitationServiceServer(grpcServer, s.Invitation)
	gen.RegisterAdminServiceServer(grpcServer, s.Admin)
	reflection.Register(grpcServer)

	return s, nil
}

func (s *GrpcServer) Run(ctx context.Context) error {
	fmt.Println("Starting gRPC server at", s.configuration.EndpointGrpcPort)
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", s.configuration.EndpointGrpcPort))
	if err != nil {
		return fmt.Errorf("failed to listen: %v", err)
	}

	if err := s.gRPC.Serve(lis); err != nil {
		return fmt.Errorf("failed to serve: %s", err)
	}
	return nil
}
