package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

----------------------------------------------------------------- */

import (
	"backend/pkg/gen"
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"

	"google.golang.org/grpc/status"

	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"

	"github.com/codefly-dev/core/wool"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

type RestServer struct {
	config *Configuration
}

func NewRestServer(c *Configuration) (*RestServer, error) {
	server := &RestServer{config: c}
	return server, nil
}

func CustomHeaderToGRPCMetadataAnnotator(ctx context.Context, req *http.Request) metadata.MD {
	return wool.MetadataFromRequest(ctx, req)
}

func customErrorHandler(ctx context.Context, mux *runtime.ServeMux, marshaler runtime.Marshaler, w http.ResponseWriter, r *http.Request, err error) {
	if runtime.HTTPStatusFromCode(status.Code(err)) == http.StatusNotFound {
		http.Error(w, "Route not found", http.StatusNotFound)
		return
	}
	runtime.DefaultHTTPErrorHandler(ctx, mux, marshaler, w, r, err)
}

func (s *RestServer) Run(ctx context.Context) error {
	fmt.Println("Starting Rest server at", *s.config.EndpointHttpPort)

	c := Cors()

	gwMux := runtime.NewServeMux(
		runtime.WithMetadata(CustomHeaderToGRPCMetadataAnnotator),
		runtime.WithErrorHandler(customErrorHandler))

	opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}
	endpoint := fmt.Sprintf("0.0.0.0:%d", s.config.EndpointGrpcPort)

	// Register all service gateways
	for _, register := range []func(context.Context, *runtime.ServeMux, string, []grpc.DialOption) error{
		gen.RegisterUserServiceHandlerFromEndpoint,
		gen.RegisterOrganizationServiceHandlerFromEndpoint,
		gen.RegisterTeamServiceHandlerFromEndpoint,
		gen.RegisterPermissionServiceHandlerFromEndpoint,
		gen.RegisterIdentityServiceHandlerFromEndpoint,
	} {
		if err := register(ctx, gwMux, endpoint, opts); err != nil {
			return err
		}
	}

	handler := c.Handler(gwMux)
	return http.ListenAndServe(fmt.Sprintf(":%d", *s.config.EndpointHttpPort), logRequestBody(handler))
}

type logResponseWriter struct {
	http.ResponseWriter
	statusCode int
}

func (rsp *logResponseWriter) WriteHeader(code int) {
	rsp.statusCode = code
	rsp.ResponseWriter.WriteHeader(code)
}

func (rsp *logResponseWriter) Unwrap() http.ResponseWriter {
	return rsp.ResponseWriter
}

func newLogResponseWriter(w http.ResponseWriter) *logResponseWriter {
	return &logResponseWriter{w, http.StatusOK}
}

func logRequestBody(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		lw := newLogResponseWriter(w)

		body, err := io.ReadAll(r.Body)
		if err != nil {
			http.Error(w, fmt.Sprintf("failed to read body: %v", err), http.StatusBadRequest)
			return
		}
		clonedR := r.Clone(r.Context())
		clonedR.Body = io.NopCloser(bytes.NewReader(body))

		h.ServeHTTP(lw, clonedR)

		if lw.statusCode != http.StatusOK {
			grpclog.Errorf("http error %+v request body %+v", lw.statusCode, string(body))
		}
	})
}
