/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/organizations/{orgId}/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminService_GetOrgEntitlements"];
        put?: never;
        post: operations["AdminService_OverrideEntitlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminService_ListActiveSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminService_SearchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}:impersonate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminService_ImpersonateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}:suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminService_SuspendUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}:unsuspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminService_UnsuspendUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["APIKeyService_ListAPIKeys"];
        put?: never;
        post: operations["APIKeyService_CreateAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["APIKeyService_RevokeAPIKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditService_QueryAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthService_GetJWKS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthService_Authenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthService_Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthService_RefreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity:resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IdentityService_ResolveIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitationService_ListInvitations"];
        put?: never;
        post: operations["InvitationService_CreateInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["InvitationService_RevokeInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitations:accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitationService_AcceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganizationService_ListOrganizations"];
        put?: never;
        post: operations["OrganizationService_CreateOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganizationService_GetOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{orgId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganizationService_ListMembers"];
        put?: never;
        post: operations["OrganizationService_AddMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{orgId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["OrganizationService_RemoveMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{orgId}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TeamService_ListTeams"];
        put?: never;
        post: operations["TeamService_CreateTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permissions:check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PermissionService_CheckPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/role-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PermissionService_AssignRole"];
        delete: operations["PermissionService_RevokeRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PermissionService_ListRoles"];
        put?: never;
        post: operations["PermissionService_CreateRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PermissionService_DeleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams/{teamId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TeamService_ListMembers"];
        put?: never;
        post: operations["TeamService_AddMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams/{teamId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["TeamService_RemoveMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_ListUsers"];
        put?: never;
        post: operations["UserService_RegisterUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_GetSelf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userUuid}/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_ListUserIdentities"];
        put?: never;
        post: operations["UserService_AddIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_GetUser"];
        put?: never;
        post?: never;
        delete: operations["UserService_DeleteUser"];
        options?: never;
        head?: never;
        patch: operations["UserService_UpdateUser"];
        trace?: never;
    };
    "/v1/users:byEmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_GetUser2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users:findByIdentity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_FindUserByIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_Version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminServiceImpersonateUserBody: Record<string, never>;
        AdminServiceOverrideEntitlementBody: {
            feature?: string;
            /** Format: int64 */
            limitValue?: string;
            reason?: string;
        };
        AdminServiceSuspendUserBody: {
            reason?: string;
        };
        AdminServiceUnsuspendUserBody: Record<string, never>;
        TeamServiceCreateTeamBody: {
            name?: string;
            description?: string;
        };
        customersAPIKey: {
            id?: string;
            organizationId?: string;
            userId?: string;
            name?: string;
            prefix?: string;
            scopes?: components["schemas"]["customersPermission"][];
            environment?: components["schemas"]["customersAPIKeyEnvironment"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
            /** Format: date-time */
            revokedAt?: string;
        };
        /**
         * @default API_KEY_ENVIRONMENT_UNSPECIFIED
         * @enum {string}
         */
        customersAPIKeyEnvironment: "API_KEY_ENVIRONMENT_UNSPECIFIED" | "API_KEY_ENVIRONMENT_LIVE" | "API_KEY_ENVIRONMENT_TEST";
        customersAcceptInvitationRequest: {
            token?: string;
        };
        customersAcceptInvitationResponse: {
            organization?: components["schemas"]["customersOrganization"];
        };
        customersAssignRoleRequest: {
            subjectId?: string;
            subjectKind?: components["schemas"]["customersSubjectKind"];
            roleId?: string;
            orgId?: string;
            scope?: string;
        };
        customersAssignRoleResponse: {
            assignment?: components["schemas"]["customersRoleAssignment"];
        };
        customersAuditEvent: {
            id?: string;
            actorId?: string;
            actorType?: string;
            action?: string;
            resource?: string;
            resourceId?: string;
            orgId?: string;
            metadata?: {
                [key: string]: string;
            };
            ipAddress?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        customersAuthenticateRequest: {
            provider?: string;
            providerId?: string;
            providerEmail?: string;
            emailVerified?: boolean;
            profile?: {
                [key: string]: string;
            };
            deviceInfo?: string;
        };
        customersAuthenticateResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            expiresIn?: string;
            user?: components["schemas"]["customersUser"];
        };
        customersCheckPermissionRequest: {
            subjectId?: string;
            subjectKind?: components["schemas"]["customersSubjectKind"];
            resource?: string;
            action?: string;
            orgId?: string;
            scope?: string;
        };
        customersCheckPermissionResponse: {
            allowed?: boolean;
            reason?: string;
        };
        customersCreateAPIKeyRequest: {
            organizationId?: string;
            name?: string;
            scopes?: components["schemas"]["customersPermission"][];
            environment?: components["schemas"]["customersAPIKeyEnvironment"];
            /** Format: date-time */
            expiresAt?: string;
        };
        customersCreateAPIKeyResponse: {
            key?: components["schemas"]["customersAPIKey"];
            plaintextKey?: string;
        };
        customersCreateInvitationRequest: {
            orgId?: string;
            email?: string;
            role?: string;
        };
        customersCreateInvitationResponse: {
            invitation?: components["schemas"]["customersInvitation"];
            inviteToken?: string;
        };
        customersCreateOrganizationRequest: {
            name?: string;
            slug?: string;
        };
        customersCreateOrganizationResponse: {
            organization?: components["schemas"]["customersOrganization"];
        };
        customersCreateRoleRequest: {
            name?: string;
            description?: string;
            permissions?: components["schemas"]["customersPermission"][];
            /** empty = global */
            orgId?: string;
        };
        customersCreateRoleResponse: {
            role?: components["schemas"]["customersRole"];
        };
        customersCreateTeamResponse: {
            team?: components["schemas"]["customersTeam"];
        };
        customersEntitlementInfo: {
            feature?: string;
            /**
             * -1 = unlimited, 0 = disabled
             * Format: int64
             */
            limit?: string;
            /** Format: int64 */
            used?: string;
            hasOverride?: boolean;
        };
        customersGetOrgEntitlementsResponse: {
            planName?: string;
            entitlements?: components["schemas"]["customersEntitlementInfo"][];
        };
        customersGetSelfResponse: {
            user?: components["schemas"]["customersUser"];
            identities?: components["schemas"]["customersUserIdentity"][];
            organizations?: components["schemas"]["customersOrganization"][];
            roleAssignments?: components["schemas"]["customersRoleAssignment"][];
        };
        customersImpersonateUserResponse: {
            accessToken?: string;
            /** Format: int64 */
            expiresIn?: string;
        };
        customersInvitation: {
            id?: string;
            orgId?: string;
            inviterId?: string;
            email?: string;
            role?: string;
            status?: components["schemas"]["customersInvitationStatus"];
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /**
         * @default INVITATION_STATUS_UNSPECIFIED
         * @enum {string}
         */
        customersInvitationStatus: "INVITATION_STATUS_UNSPECIFIED" | "INVITATION_STATUS_PENDING" | "INVITATION_STATUS_ACCEPTED" | "INVITATION_STATUS_REVOKED" | "INVITATION_STATUS_EXPIRED";
        customersJWKSResponse: {
            keysJson?: string;
        };
        customersListAPIKeysResponse: {
            keys?: components["schemas"]["customersAPIKey"][];
            nextPageToken?: string;
        };
        customersListActiveSessionsResponse: {
            sessions?: components["schemas"]["customersSessionInfo"][];
            nextPageToken?: string;
        };
        customersListInvitationsResponse: {
            invitations?: components["schemas"]["customersInvitation"][];
        };
        customersListOrgMembersResponse: {
            members?: components["schemas"]["customersOrgMembership"][];
        };
        customersListOrganizationsResponse: {
            organizations?: components["schemas"]["customersOrganization"][];
        };
        customersListRolesResponse: {
            roles?: components["schemas"]["customersRole"][];
        };
        customersListTeamMembersResponse: {
            members?: components["schemas"]["customersTeamMembership"][];
        };
        customersListTeamsResponse: {
            teams?: components["schemas"]["customersTeam"][];
        };
        customersListUserIdentitiesResponse: {
            identities?: components["schemas"]["customersUserIdentity"][];
        };
        customersListUsersResponse: {
            users?: components["schemas"]["customersUser"][];
            nextPageToken?: string;
        };
        customersLogoutRequest: {
            refreshToken?: string;
        };
        customersOrgMembership: {
            orgId?: string;
            userId?: string;
            role?: components["schemas"]["customersOrgRole"];
            /** Format: date-time */
            joinedAt?: string;
        };
        /**
         * @default ORG_ROLE_UNSPECIFIED
         * @enum {string}
         */
        customersOrgRole: "ORG_ROLE_UNSPECIFIED" | "ORG_ROLE_MEMBER" | "ORG_ROLE_ADMIN" | "ORG_ROLE_OWNER";
        customersOrganization: {
            id?: string;
            name?: string;
            slug?: string;
            ownerId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        customersOrganizationServiceAddMemberBody: {
            userId?: string;
            role?: components["schemas"]["customersOrgRole"];
        };
        customersOverrideEntitlementResponse: {
            id?: string;
        };
        customersPermission: {
            resource?: string;
            action?: string;
        };
        customersQueryAuditLogResponse: {
            events?: components["schemas"]["customersAuditEvent"][];
            nextPageToken?: string;
            /** Format: int32 */
            totalCount?: number;
        };
        customersRefreshTokenRequest: {
            refreshToken?: string;
        };
        customersRefreshTokenResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            expiresIn?: string;
        };
        customersRegisterUserRequest: {
            primaryEmail?: string;
            profile?: {
                [key: string]: string;
            };
            identity?: components["schemas"]["customersUserIdentity"];
        };
        customersRegisterUserResponse: {
            user?: components["schemas"]["customersUser"];
            identity?: components["schemas"]["customersUserIdentity"];
        };
        customersResolveIdentityRequest: {
            provider?: string;
            providerId?: string;
        };
        customersResolveIdentityResponse: {
            userId?: string;
            orgId?: string;
            roles?: string[];
            found?: boolean;
        };
        customersRole: {
            id?: string;
            name?: string;
            description?: string;
            permissions?: components["schemas"]["customersPermission"][];
            builtIn?: boolean;
            /** empty = global */
            orgId?: string;
        };
        customersRoleAssignment: {
            id?: string;
            subjectId?: string;
            subjectKind?: components["schemas"]["customersSubjectKind"];
            roleId?: string;
            orgId?: string;
            /** optional fine-grained scope */
            scope?: string;
            /** Format: date-time */
            assignedAt?: string;
        };
        customersSearchUsersResponse: {
            users?: components["schemas"]["customersUser"][];
            nextPageToken?: string;
            /** Format: int32 */
            totalCount?: number;
        };
        customersSessionInfo: {
            id?: string;
            userId?: string;
            ipAddress?: string;
            deviceInfo?: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastActiveAt?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        /**
         * @default SUBJECT_KIND_UNSPECIFIED
         * @enum {string}
         */
        customersSubjectKind: "SUBJECT_KIND_UNSPECIFIED" | "SUBJECT_KIND_USER" | "SUBJECT_KIND_TEAM";
        customersTeam: {
            id?: string;
            orgId?: string;
            name?: string;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        customersTeamMembership: {
            teamId?: string;
            userId?: string;
            role?: components["schemas"]["customersTeamRole"];
            /** Format: date-time */
            joinedAt?: string;
        };
        /**
         * @default TEAM_ROLE_UNSPECIFIED
         * @enum {string}
         */
        customersTeamRole: "TEAM_ROLE_UNSPECIFIED" | "TEAM_ROLE_MEMBER" | "TEAM_ROLE_ADMIN" | "TEAM_ROLE_OWNER";
        customersTeamServiceAddMemberBody: {
            userId?: string;
            role?: components["schemas"]["customersTeamRole"];
        };
        /** User represents a user in the system */
        customersUser: {
            uuid?: string;
            primaryEmail?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            lastLogin?: string;
            status?: components["schemas"]["customersUserStatus"];
            profile?: {
                [key: string]: string;
            };
            emailVerified?: boolean;
        };
        /** UserIdentity represents a user's authentication method */
        customersUserIdentity: {
            uuid?: string;
            userUuid?: string;
            provider?: string;
            providerId?: string;
            providerEmail?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsed?: string;
            providerData?: {
                [key: string]: string;
            };
            emailVerified?: boolean;
        };
        /**
         * @default USER_STATUS_UNSPECIFIED
         * @enum {string}
         */
        customersUserStatus: "USER_STATUS_UNSPECIFIED" | "USER_STATUS_ACTIVE" | "USER_STATUS_INACTIVE" | "USER_STATUS_SUSPENDED" | "USER_STATUS_DELETED";
        customersVersionResponse: {
            version?: string;
        };
        protobufAny: {
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        rpcStatus: {
            /** Format: int32 */
            code?: number;
            message?: string;
            details?: components["schemas"]["protobufAny"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminService_GetOrgEntitlements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersGetOrgEntitlementsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AdminService_OverrideEntitlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminServiceOverrideEntitlementBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersOverrideEntitlementResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AdminService_ListActiveSessions: {
        parameters: {
            query?: {
                userId?: string;
                pageSize?: number;
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersListActiveSessionsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AdminService_SearchUsers: {
        parameters: {
            query?: {
                query?: string;
                pageSize?: number;
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersSearchUsersResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AdminService_ImpersonateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminServiceImpersonateUserBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersImpersonateUserResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AdminService_SuspendUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminServiceSuspendUserBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AdminService_UnsuspendUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminServiceUnsuspendUserBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    APIKeyService_ListAPIKeys: {
        parameters: {
            query?: {
                organizationId?: string;
                pageSize?: number;
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersListAPIKeysResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    APIKeyService_CreateAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersCreateAPIKeyRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersCreateAPIKeyResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    APIKeyService_RevokeAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AuditService_QueryAuditLog: {
        parameters: {
            query?: {
                orgId?: string;
                actorId?: string;
                action?: string;
                resource?: string;
                resourceId?: string;
                from?: string;
                to?: string;
                pageSize?: number;
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersQueryAuditLogResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AuthService_GetJWKS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersJWKSResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AuthService_Authenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersAuthenticateRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersAuthenticateResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AuthService_Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersLogoutRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AuthService_RefreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersRefreshTokenRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersRefreshTokenResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    IdentityService_ResolveIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersResolveIdentityRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersResolveIdentityResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    InvitationService_ListInvitations: {
        parameters: {
            query?: {
                orgId?: string;
                status?: "INVITATION_STATUS_UNSPECIFIED" | "INVITATION_STATUS_PENDING" | "INVITATION_STATUS_ACCEPTED" | "INVITATION_STATUS_REVOKED" | "INVITATION_STATUS_EXPIRED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersListInvitationsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    InvitationService_CreateInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersCreateInvitationRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersCreateInvitationResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    InvitationService_RevokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    InvitationService_AcceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersAcceptInvitationRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersAcceptInvitationResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    OrganizationService_ListOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersListOrganizationsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    OrganizationService_CreateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersCreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersCreateOrganizationResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    OrganizationService_GetOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersOrganization"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    OrganizationService_ListMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersListOrgMembersResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    OrganizationService_AddMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersOrganizationServiceAddMemberBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    OrganizationService_RemoveMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    TeamService_ListTeams: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersListTeamsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    TeamService_CreateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamServiceCreateTeamBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersCreateTeamResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    PermissionService_CheckPermission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersCheckPermissionRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersCheckPermissionResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    PermissionService_AssignRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersAssignRoleRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersAssignRoleResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    PermissionService_RevokeRole: {
        parameters: {
            query?: {
                subjectId?: string;
                roleId?: string;
                orgId?: string;
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    PermissionService_ListRoles: {
        parameters: {
            query?: {
                /** @description empty = list global roles */
                orgId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersListRolesResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    PermissionService_CreateRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersCreateRoleRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersCreateRoleResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    PermissionService_DeleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    TeamService_ListMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersListTeamMembersResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    TeamService_AddMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersTeamServiceAddMemberBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    TeamService_RemoveMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_ListUsers: {
        parameters: {
            query?: {
                pageSize?: number;
                pageToken?: string;
                status?: "USER_STATUS_UNSPECIFIED" | "USER_STATUS_ACTIVE" | "USER_STATUS_INACTIVE" | "USER_STATUS_SUSPENDED" | "USER_STATUS_DELETED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersListUsersResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_RegisterUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersRegisterUserRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersRegisterUserResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_GetSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersGetSelfResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_ListUserIdentities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersListUserIdentitiesResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_AddIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersUserIdentity"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersUserIdentity"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_GetUser: {
        parameters: {
            query?: {
                email?: string;
            };
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersUser"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_DeleteUser: {
        parameters: {
            query?: {
                email?: string;
            };
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_UpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["customersUser"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersUser"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_GetUser2: {
        parameters: {
            query?: {
                uuid?: string;
                email?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersUser"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_FindUserByIdentity: {
        parameters: {
            query?: {
                provider?: string;
                providerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersUser"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    UserService_Version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["customersVersionResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
}
