name: CI

on: [push, pull_request]

jobs:
  run-codefly-ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Codefly CI Test
        uses: codefly-dev/github-action@v0.0.6
        with:
          subfolder: templates/factory
